# Generated by Django 5.1.2 on 2025-02-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='url',
            field=models.CharField(blank=True, default='no_url', max_length=100, null=True),
        ),
    ]
