# Generated by Django 5.1.2 on 2025-02-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businesstype_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='product_card_template',
            field=models.FileField(blank=True, null=True, upload_to='business/'),
        ),
        migrations.AddField(
            model_name='business',
            name='product_detail_template',
            field=models.FileField(blank=True, null=True, upload_to='business/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='html_template',
            field=models.FileField(blank=True, null=True, upload_to='business/'),
        ),
    ]
