# Generated by Django 5.1.2 on 2025-02-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_business_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='business/'),
        ),
    ]
