# Generated by Django 5.1.2 on 2025-02-22 10:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_business_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.business_bg_path),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.business_logo_path),
        ),
        migrations.AlterField(
            model_name='business',
            name='html_template',
            field=models.FileField(blank=True, null=True, upload_to=core.models.html_template_path),
        ),
    ]
