# Generated by Django 5.1.2 on 2025-05-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_business_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='slug',
            field=models.SlugField(blank=True, default='no_slug', max_length=100, null=True),
        ),
    ]
