# Generated by Django 5.1.2 on 2025-06-22 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_businesstype_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location_type', models.CharField(choices=[('warehouse', 'Склад'), ('store', 'Магазин'), ('restaurant', 'Ресторан'), ('mixed', 'Склад и точка продаж')], default='mixed', max_length=20, verbose_name='Тип локации')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основная локация')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('opening_hours', models.JSONField(blank=True, help_text="Формат: {'monday': {'open': '09:00', 'close': '21:00'}, ...}", null=True, verbose_name='Часы работы')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.business', verbose_name='Бизнес')),
            ],
            options={
                'verbose_name': 'Локация бизнеса',
                'verbose_name_plural': 'Локации бизнеса',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
