# Generated by Django 5.1.2 on 2025-06-26 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_businesslocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код типа')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание типа')),
                ('is_warehouse', models.BooleanField(default=False, verbose_name='Является складом')),
                ('is_sales_point', models.BooleanField(default=False, verbose_name='Является точкой продаж')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тип локации бизнеса',
                'verbose_name_plural': 'Типы локаций бизнеса',
            },
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='core.businesslocationtype', verbose_name='Тип локации'),
        ),
    ]
