# Generated by Django 5.1.2 on 2025-07-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businesslocationtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='receipt_css_template',
            field=models.TextField(blank=True, help_text='CSS стили для генерации PDF чека', null=True, verbose_name='CSS стили чека'),
        ),
        migrations.AddField(
            model_name='business',
            name='receipt_html_template',
            field=models.TextField(blank=True, help_text='HTML шаблон для генерации PDF чека', null=True, verbose_name='HTML шаблон чека'),
        ),
    ]
