# Generated by Django 5.1.2 on 2025-02-01 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_floors', models.PositiveIntegerField(default=1, help_text='Сколько этажей в ТЦ')),
                ('opening_hours', models.CharField(blank=True, help_text="Часы работы, например '10:00 - 22:00'", max_length=255, null=True)),
                ('parking_spots', models.PositiveIntegerField(blank=True, help_text='Количество парковочных мест, если актуально', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mall', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='MallFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.CharField(help_text="Условное обозначение этажа, например '1', '2', '3', '-1' (паркинг)", max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='mall.mall')),
            ],
        ),
        migrations.CreateModel(
            name='MallShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, help_text='Открыт ли магазин сейчас?')),
                ('description', models.TextField(blank=True, help_text='Доп. описание расположения, ассортимента и т. д.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mall_shop', to='core.business')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='mall.mallfloor')),
            ],
        ),
    ]
