# Generated by Django 5.1.2 on 2025-05-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_productvariant_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='show_attribute_at_right',
            field=models.BooleanField(default=False, help_text='Показывать атрибут в правой части страницы товара для выбора'),
        ),
    ]
