# Generated by Django 5.1.2 on 2025-06-22 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_businesslocation'),
        ('marketplace', '0003_categoryattribute_show_attribute_at_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Зарезервированное количество')),
                ('is_available_for_sale', models.BooleanField(default=True, help_text='Если отмечено, товар можно продавать в этой локации', verbose_name='Доступен для продажи')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Остаток товара',
                'verbose_name_plural': 'Остатки товаров',
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['price'], 'verbose_name': 'Вариант товара', 'verbose_name_plural': 'Варианты товаров'},
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='marketplace_stock_q_880e67_idx',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='productstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='core.businesslocation', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='marketplace.productvariant', verbose_name='Вариант товара'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='locations',
            field=models.ManyToManyField(related_name='product_variants', through='marketplace.ProductStock', to='core.businesslocation', verbose_name='Локации'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['variant', 'location'], name='marketplace_variant_eca143_idx'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['is_available_for_sale'], name='marketplace_is_avai_8b03a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('variant', 'location')},
        ),
    ]
