# Generated by Django 5.1.2 on 2025-07-03 10:36

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_productstock_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.variants_barcode_path),
        ),
    ]
