# Generated by Django 5.1.2 on 2025-02-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_attribute_categoryattribute_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='page_identificator',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
