# Generated by Django 5.1.2 on 2025-02-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_category_depth_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='big_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='category_images/big_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='small_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='category_images/small_images/'),
        ),
    ]
