# Generated by Django 5.1.2 on 2025-07-06 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_product_marketplace_on_the__1be3cb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='marketplace.productstock', verbose_name='Остаток')),
            ],
            options={
                'verbose_name': 'Брак товара',
                'verbose_name_plural': 'Брак товара',
            },
        ),
    ]
