# Generated by Django 5.1.2 on 2025-07-10 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businesslocationtype_and_more'),
        ('marketplace', '0007_productdefect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Уникальный идентификатор, например 'cash', 'card', 'kaspi_qr'", max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(help_text='Отображаемое название способа оплаты', max_length=64, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер чека')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая сумма')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Имя клиента (если нет аккаунта)')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон клиента')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.paymentmethod', verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма продажи')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False, help_text='True если заказ сделан через интернет', verbose_name='Онлайн покупка')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.businesslocation', verbose_name='Локация продажи')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='marketplace.productvariant', verbose_name='Вариант товара')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='marketplace.receipt', verbose_name='Чек')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-sale_date'],
            },
        ),
    ]
