# Generated by Django 5.1.2 on 2025-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_paymentmethod_receipt_productsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='is_online',
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_online',
            field=models.BooleanField(default=False, help_text='True если заказ сделан через интернет', verbose_name='Онлайн покупка'),
        ),
    ]
