# Generated by Django 5.1.2 on 2025-02-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
