# Generated by Django 5.1.2 on 2025-07-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_productsale_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя клиента (если нет аккаунта)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон клиента'),
        ),
    ]
