# Generated by Django 5.1.2 on 2025-02-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_the_main',
            field=models.BooleanField(default=False),
        ),
    ]
