# Generated by Django 5.1.2 on 2025-07-21 22:50

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_receipt_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=marketplace.models.receipt_pdf_path, verbose_name='Файл PDF чека'),
        ),
    ]
