# Generated by Django 5.1.2 on 2025-02-22 10:36

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_product_on_the_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=marketplace.models.product_image_path),
        ),
    ]
