# Generated by Django 5.1.2 on 2025-07-21 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_receipt_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='pdf_file',
            new_name='receipt_pdf_file',
        ),
    ]
