# Generated by Django 5.1.2 on 2025-07-29 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_receipt_receipt_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='marketplace.receipt', verbose_name='Чек'),
        ),
    ]
