# Generated by Django 5.1.2 on 2025-07-29 13:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_alter_productsale_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReceipt',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=100, verbose_name='Номер чека')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая сумма')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя клиента (если нет аккаунта)')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон клиента')),
                ('receipt_preview_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Превью чека (jpg/png)')),
                ('receipt_pdf_file', models.TextField(blank=True, max_length=100, null=True, verbose_name='Файл PDF чека')),
                ('is_online', models.BooleanField(default=False, help_text='True если заказ сделан через интернет', verbose_name='Онлайн покупка')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketplace.paymentmethod', verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'historical Чек',
                'verbose_name_plural': 'historical Чеки',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
