# Generated by Django 5.1.2 on 2025-07-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_historicalreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceipt',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён'),
        ),
    ]
