# Generated by Django 5.1.2 on 2025-07-31 15:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_business_receipt_css_template_and_more'),
        ('marketplace', '0017_historicalreceipt_is_deleted_receipt_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductDefect',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketplace.productstock', verbose_name='Остаток')),
            ],
            options={
                'verbose_name': 'historical Брак товара',
                'verbose_name_plural': 'historical Брак товара',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductStock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Зарезервированное количество')),
                ('is_available_for_sale', models.BooleanField(default=True, help_text='Если отмечено, товар можно продавать в этой локации', verbose_name='Доступен для продажи')),
                ('last_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Последнее обновление')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.businesslocation', verbose_name='Локация')),
                ('variant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketplace.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'historical Остаток товара',
                'verbose_name_plural': 'historical Остатки товаров',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductVariant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('barcode_image', models.TextField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Артикул')),
                ('has_custom_name', models.BooleanField(default=False, help_text='Если отмечено, для этого варианта будет использоваться собственное название', verbose_name='Использовать своё название')),
                ('custom_name', models.CharField(blank=True, help_text='Название этого варианта (если отличается от основного товара)', max_length=255, null=True, verbose_name='Своё название')),
                ('has_custom_description', models.BooleanField(default=False, help_text='Если отмечено, для этого варианта будет использоваться собственное описание', verbose_name='Использовать своё описание')),
                ('custom_description', models.TextField(blank=True, help_text='Описание этого варианта (если отличается от основного товара)', null=True, verbose_name='Своё описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Процент скидки')),
                ('show_this', models.BooleanField(default=False, help_text='Если отмечено, этот вариант будет показан в результатах поиска и списках товаров', verbose_name='Показывать в поиске')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketplace.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'historical Вариант товара',
                'verbose_name_plural': 'historical Варианты товаров',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
